correct

diff --git a/0x12-web_stack_debugging_2/0-iamsomeoneelse b/0x12-web_stack_debugging_2/0-iamsomeoneelse
--- a/0x12-web_stack_debugging_2/0-iamsomeoneelse
+++ b/0x12-web_stack_debugging_2/0-iamsomeoneelse
@@ -1,4 +1,7 @@
 #!/usr/bin/env bash
 # The script that run the whoami command under the user passed as an argument
-
-su "$1" -s /bin/bash -c 'whoami'
+if [ -z "$1" ]; then
+  echo "User cannot be empty or null."
+  exit 1
+fi
+sudo -u "$1" whoami
